name: Tests for IQL, MAPPO, VDN algo

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.18'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-opengl
          pip install -r requirements.txt
          pip install opencv-python-headless
          AutoROM -y

      - name: Run tests for IQL
        run: python -m tests.test_training_framework --algo IQL

      - name: Run tests for VDN
        run: python -m tests.test_training_framework --algo VDN

      - name: Run tests for MAPPO
        run: python -m tests.test_training_framework --algo MAPPO