name: Tests on latest tag

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.18'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-opengl
          pip install -r requirements.txt
          pip install opencv-python-headless
          AutoROM -y

      - name: Run tests # For now we will run only the tests about the envs API. Later we will use a self-hosted runner to run the full test suite.
        run: python -m unittest tests.test_envs_api

