name: Tests on latest tag 3.10

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake swig build-essential python3-dev python3-opengl cmake swig g++-9 gcc-9
          sudo apt-get install -y libboost-all-dev libsdl2-dev libsdl2-image-dev libjpeg-dev zlib1g-dev
          export CC=gcc-9 CXX=g++-9

      - name: Upgrade pip & build tools
        run: python -m pip install --upgrade pip==25.1 setuptools==78.1.1 wheel==0.45.1

      - name: Install Python deps
        run: |
          python -m pip install opencv-python-headless
          python -m pip install autorom[accept-rom-license]
          python -m pip install -r requirements.txt

      - name: Run Python script to automate AutoROM
        run: python tests/autorom_run.py

      - name: Run tests
        run: python -m unittest tests.test_envs_api

