name: Tests for MAA2C, IA2C, QMIX algo

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.18'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-opengl
          pip install -r requirements.txt
          pip install opencv-python-headless
          AutoROM -y

      - name: Run tests for MAA2C
        run: python -m tests.test_training_framework --algo MAA2C

      - name: Run tests for IA2C
        run: python -m tests.test_training_framework --algo IA2C

      - name: Run tests for QMIX
        run: python -m tests.test_training_framework --algo QMIX
